module.exports = {
  mySidebar: [
    "intro",
    {
      type: "category",
      label: "Tuto",
      items: [
        "tuto",
        {
          type: "autogenerated",
          dirName: "tuto" // Génère une barre latérale à partir de docs/tutorials/easy
        }
      ]
    }
  ]
};
